routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes([
  'verify' => true,
  'reset'  => false
]);

Route::redirect('/', '/bulletin')->name('home');

Route::name('gallery.')->group(function (){

  Route::get('{locale}/gallery', 'GalleryController@index')->name('index');
  Route::get('{locale}/gallery/images', 'GalleryController@gallery')->name('images');
  Route::post('/gallery', 'GalleryController@store')->name('store');
  Route::get('{gallery}/edit/{locale}', 'GalleryController@edit')->name('edit');
  Route::put('/gallery/{gallery}', 'GalleryController@update')->name('update');
  Route::get('{gallery}/delete/{locale}', 'GalleryController@confirmDelete')->name('delete');
  Route::delete('/gallery/{gallery}', 'GalleryController@destroy')->name('destroy');
  
});

Route::get('/contact', 'ContactController@index')->name('contact');
Route::post('/contact', 'ContactController@sendMail')->name('send');

Route::resource('bulletin', 'BulletinController')->except(['create', 'show']);
Route::get('/bulletin/{bulletin}/delete', 'BulletinController@delete')->name('bulletin.delete');

Route::prefix('register')->group(function (){

  Route::post('validation', 'Auth\RegisterController@validator')->name('register.validation');
  Route::post('create', 'Auth\RegisterController@create')->name('register.create');

  Route::get('confirmation', function (){
    return view('auth.register-confirmation');
  })->name('register.confirmation');

  Route::get('success', function (){
    return view('auth.verify');
  })->name('email.verification');

});

Route::get('success', function (){
  return view('auth.verification-success');
})->name('registered');


Route::name('admin.')->group(function (){
	
	Route::get('/admin/login', 'AdminController@showLoginForm')->name('login.form');
	Route::post('/admin/login', 'AdminController@login')->name('login');
	
  Route::get('/admin', 'AdminController@dashboard')->name('dashboard');
  Route::get('/admin/contact', 'AdminController@contact')->name('contact');
	
});

resources/views/admin/contact.blade.php
@extends('layouts.admin')

@section('title', 'Timedoor Admin | Dashboard')

@section('content')
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>T</b>D</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Timedoor</b> Admin</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="hidden-xs">Hello, Admin </span>
                </a>
                <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">
                    <img src="img/user-ico.jpg" class="img-circle" alt="User Image">
                    <p>
                    Administrator
                    </p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                    <div class="text-right">
                    <a href="login.php" class="btn btn-danger btn-flat">Sign out</a>
                    </div>
                </li>
                </ul>
            </li>
            </ul>
        </div>
        </nav>
    </header>

    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        @include('admin.components.sidebar')
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
        <h1>
            Contact
            <small>Email</small>
        </h1>
        </section>

        <!-- Main content -->
        <section class="content">
        <div class="row">
            <div class="col-xs-12">
            <!-- /.col-xs-12 -->
            <div class="box box-success">
                <div class="box-header with-border">
                <h1 class="font-18 m-0">Timedoor Challenge</h1>
                </div>
                <form method="" action="">
                <div class="box-body">
                    <table class="table table-bordered">
                    <thead>
                        <tr>
                        <th>
                            <input type="checkbox" id="check-all">
                        </th>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Body</th>
                        <th width="50">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Foreach -->
                        @foreach ($contacts as $contact)
                        <tr>
                            <td>
                                <input type="checkbox">
                            </td>
                            <td>{{ $contact->id }}</td>
                            <td>{{ $contact->name }}</td>
                            <td>{{ $contact->phone }}</td>
                            <td>{{ $contact->email }}</td>
                            <td>{{ $contact->body }}</td>
                            <td><a href="#" data-toggle="modal" data-target="#deleteModal" class="btn btn-danger" rel="tooltip" title="Delete"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                        @endforeach
                        <!-- End Foreach -->
                    </tbody>
                    </table>
                    <a href="#" class="btn btn-default mt-5" data-toggle="modal" data-target="#deleteModal">Delete Checked Items</a>
                    <div class="text-center">
                    <!-- Pagination -->
                    <div class="text-center mt-30">
                        <nav>
                            {{ $contacts->links() }}
                        </nav>
                    </div>
                    </div>
                </div>
                </form>
            </div>
            </div>
            <!-- /.col-xs-12 -->
        </div>
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 0.1.0
        </div>
        <strong>Copyright &copy; {{ date('Y') }} <a href="https://timedoor.net" class="text-green">Timedoor Indonesia</a>.</strong> All rights reserved.
    </footer>
</div>
@endsection

resources/views/admin/gallery.blade.php
@extends('layouts.admin')

@section('title', 'Timedoor Admin | Gallery')

@section('content')
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>T</b>D</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Timedoor</b> Admin</span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="hidden-xs">Hello, Admin </span>
                </a>
                <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">
                    <p>
                    Administrator
                    </p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                    <div class="text-right">
                    <a href="login.php" class="btn btn-danger btn-flat">Sign out</a>
                    </div>
                </li>
                </ul>
            </li>
            </ul>
        </div>
        </nav>
    </header>

    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        @include('admin.components.sidebar')
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
        <h1>
            Gallery
        </h1>
        </section>

        <!-- Main content -->
        <section class="content">
        <div class="row">
            <div class="col-xs-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        @foreach ($errors->all() as $error)
                        {{ $error }}
                        <br>
                        @endforeach
                    </div>
                @elseif (session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                <div class="box box-success">
                    <div class="box-header with-border">
                        <h1 class="font-18 m-0">Timedoor Challenge</h1>
                    </div>
                    <div class="box-body">
                        <div class="bordered-box mb-20">
                            <form action="{{ route('gallery.store') }}" method="post" enctype="multipart/form-data">
                            @csrf

                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="{{ route('gallery.index', 'en') }}"><img src="{{ asset('icons/uk.png') }}" width="15"> en</a></li>
                                <li><a href="{{ route('gallery.index', 'jp') }}"><img src="{{ asset('icons/jp.png') }}" width="15"> jp</a></li>
                                <li><a href="{{ route('gallery.index', 'id') }}"><img src="{{ asset('icons/id.png') }}" width="15"> id</a></li>
                            </ul>

                            <input type="hidden" name="locale" value="{{ app()->getLocale() }}">

                            <table class="table table-no-border mb-0">
                                <tbody>
                                    <tr>
                                        <td>
                                            <div class="form-group">
                                                <label>Choose image from your computer :</label>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <input type="text" class="form-control upload-form" value="No file chosen" readonly>
                                                    <span class="input-group-btn">
                                                        <span class="btn btn-default btn-file">
                                                            <i class="fa fa-folder-open"></i>&nbsp;Browse <input type="file" name="image">
                                                        </span>
                                                    </span>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <button type="button" class="btn btn-primary form-control" data-toggle="modal" data-target="#inputModal">Next</button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <table class="table">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Title</th>
                                    <th>Alt Image</th>
                                    <th>Desc Image</th>
                                    <th>Image</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $i = 1; ?>
                                @foreach ($galleries as $gallery)
                                    <tr>
                                        <td>{{ $i++ . '.' }}</td>
                                        <td>{{ $gallery->image->title }}</td>
                                        <td>{{ $gallery->image->alt_desc }}</td>
                                        <td>{{ $gallery->image->desc }}</td>
                                        <td><img src="{{ $render($gallery->image->name) }}" alt="{{ $gallery->image->alt_desc }}" width="100"></td>
                                        <td>
                                            <a href="{{ route('gallery.edit', [$gallery->id, app()->getLocale()]) }}"><i class="fa fa-pencil"></i> Edit</a>
                                            <br>
                                            <a class="text-danger" href="{{ route('gallery.delete', [$gallery->id, app()->getLocale()]) }}"><i class="fa fa-trash"></i> Delete</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 0.1.0
        </div>
        <strong>Copyright &copy; {{ date('Y') }} <a href="https://timedoor.net" class="text-green">Timedoor Indonesia</a>.</strong> All rights reserved.
    </footer>
</div>

@include('admin.components.modals')
@endsection

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('title', 'Timedoor Admin | Dashboard')

@section('content')
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>T</b>D</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Timedoor</b> Admin</span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs">Hello, Admin </span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="img/user-ico.jpg" class="img-circle" alt="User Image">
                <p>
                  Administrator
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="text-right">
                  <a href="login.php" class="btn btn-danger btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    @include('admin.components.sidebar')
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <!-- /.col-xs-12 -->
          <div class="box box-success">
            <div class="box-header with-border">
              <h1 class="font-18 m-0">Timedoor Challenge - Level 9</h1>
            </div>
            <form method="" action="">
              <div class="box-body">
                <div class="bordered-box mb-20">
                  <form class="form" role="form">
                    <table class="table table-no-border mb-0">
                      <tbody>
                        <tr>
                          <td width="80"><b>Title</b>
                          </td>
                          <td>
                            <div class="form-group mb-0">
                              <input type="text" class="form-control">
                            </div>
                          </td>
                        </tr>
                        <tr>
                          <td><b>Body</b>
                          </td>
                          <td>
                            <div class="form-group mb-0">
                              <input type="text" class="form-control">
                            </div>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    <table class="table table-search">
                      <tbody>
                        <tr>
                          <td width="80"><b>Image</b>
                          </td>
                          <td width="60">
                            <label class="radio-inline">
                              <input type="radio" name="imageOption" id="inlineRadio1" value="option1"> with
                            </label>
                          </td>
                          <td width="80">
                            <label class="radio-inline">
                              <input type="radio" name="imageOption" id="inlineRadio2" value="option2"> without
                            </label>
                          </td>
                          <td>
                            <label class="radio-inline">
                              <input type="radio" name="imageOption" id="inlineRadio3" value="option3" checked> unspecified
                            </label>
                          </td>
                        </tr>
                        <tr>
                          <td width="80"><b>Status</b>
                          </td>
                          <td>
                            <label class="radio-inline">
                              <input type="radio" name="statusOption" id="inlineRadio1" value="option1"> on
                            </label>
                          </td>
                          <td>
                            <label class="radio-inline">
                              <input type="radio" name="statusOption" id="inlineRadio2" value="option2"> delete
                            </label>
                          </td>
                          <td>
                            <label class="radio-inline">
                              <input type="radio" name="statusOption" id="inlineRadio3" value="option3" checked> unspecified
                            </label>
                          </td>
                        </tr>
                        <tr>
                          <td><a href="#" class="btn btn-default mt-10"><i class="fa fa-search"></i> Search</a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </form>
                </div>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>
                        <input type="checkbox" id="check-all">
                      </th>
                      <th>ID</th>
                      <th>Title</th>
                      <th>Body</th>
                      <th width="200">Image</th>
                      <th>Date</th>
                      <th width="50">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>
                        <input type="checkbox">
                      </td>
                      <td>330</td>
                      <td>Lorem Ipsum</td>
                      <td>Lorem ipsum dolor sit amet, consectar bla bla bla...</td>
                      <td>
                        <img class="img-prev" src="https://via.placeholder.com/500x500">
                        <a href="#" data-toggle="modal" data-target="#deleteModal" class="btn btn-danger ml-10 btn-img" rel="tooltip" title="Delete Image"><i class="fa fa-trash"></i></a>
                      </td>
                      <td>2014/7/9
                        <br><span class="small">13:59:00</span>
                      </td>
                      <td><a href="#" data-toggle="modal" data-target="#deleteModal" class="btn btn-danger" rel="tooltip" title="Delete"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                    <tr class="bg-gray-light">
                      <td>&nbsp;</td>
                      <td>331</td>
                      <td>Lorem Ipsum</td>
                      <td>Lorem ipsum dolor sit amet, consectar bla bla bla...</td>
                      <td>
                        -
                      </td>
                      <td>2014/7/9
                        <br><span class="small">13:59:00</span>
                      </td>
                      <td><a href="#" class="btn btn-default" rel="tooltip" title="Recover"><i class="fa fa-repeat"></i></a>
                      </td>
                    </tr>
                  </tbody>
                </table>
                <a href="#" class="btn btn-default mt-5" data-toggle="modal" data-target="#deleteModal">Delete Checked Items</a>
                <div class="text-center">
                  <nav>
                    <ul class="pagination">
                      <li><a href="#">&laquo;</a>
                      </li>
                      <li class="active"><a href="#">1</a>
                      </li>
                      <li><a href="#">2</a>
                      </li>
                      <li><a href="#">3</a>
                      </li>
                      <li><a href="#">&raquo;</a>
                      </li>
                    </ul>
                    {{-- $bulletins->links() --}}
                  </nav>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- /.col-xs-12 -->
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 0.1.0
    </div>
    <strong>Copyright &copy; {{ date('Y') }} <a href="https://timedoor.net" class="text-green">Timedoor Indonesia</a>.</strong> All rights reserved.
  </footer>

  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
          </button>
          <div class="text-center">
            <h4 class="modal-title" id="myModalLabel">Delete Data</h4>
          </div>
        </div>
        <div class="modal-body pad-20">
          <p>Are you sure want to delete this item(s)?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-danger">Delete</button>
        </div>
      </div>
    </div>
  </div>

</div>
@endsection