routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes([
  'verify' => true,
  'reset'  => false
]);

Route::redirect('/', '/bulletin')->name('home');

Route::name('gallery.')->group(function (){

  Route::get('{locale}/gallery', 'GalleryController@index')->name('index');
  Route::get('{locale}/gallery/images', 'GalleryController@gallery')->name('images');
  Route::post('/gallery', 'GalleryController@store')->name('store');
  Route::get('{gallery}/edit/{locale}', 'GalleryController@edit')->name('edit');
  Route::put('/gallery/{gallery}', 'GalleryController@update')->name('update');
  Route::get('{gallery}/delete/{locale}', 'GalleryController@confirmDelete')->name('delete');
  Route::delete('/gallery/{gallery}', 'GalleryController@destroy')->name('destroy');
  
});

Route::get('/contact', 'ContactController@index')->name('contact');
Route::post('/contact', 'ContactController@sendMail')->name('send');

Route::resource('bulletin', 'BulletinController')->except(['create', 'show']);
Route::get('/bulletin/{bulletin}/delete', 'BulletinController@delete')->name('bulletin.delete');

Route::prefix('register')->group(function (){

  Route::post('validation', 'Auth\RegisterController@validator')->name('register.validation');
  Route::post('create', 'Auth\RegisterController@create')->name('register.create');

  Route::get('confirmation', function (){
    return view('auth.register-confirmation');
  })->name('register.confirmation');

  Route::get('success', function (){
    return view('auth.verify');
  })->name('email.verification');

});

Route::get('success', function (){
  return view('auth.verification-success');
})->name('registered');


Route::name('admin.')->group(function (){
	
	Route::get('/admin/login', 'AdminController@showLoginForm')->name('login.form');
	Route::post('/admin/login', 'AdminController@login')->name('login');
	
  Route::get('/admin', 'AdminController@dashboard')->name('dashboard');
  Route::get('/admin/contact', 'AdminController@contact')->name('contact');
	
});

resources/views/bulletin-board/components/modals.blade.php
@if ( Route::is('bulletin.index') )

  @php $id = session('bulletin.id') ?? session('input.id') @endphp

  <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Edit Item</h4>
        </div>

        <form action="{{ route('bulletin.update', $id) }}" method="post" enctype="multipart/form-data">

          <div class="modal-body">

            @if ($errors->patch->any())
              <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading"><strong>Whoops!</strong></h4>
                @foreach ($errors->patch->all() as $error)
                  {{ $error }}
                  <br>
                @endforeach
              </div>
            @endif

            @method('PATCH')
            @csrf

            @php
              $name = (session('name') === 'No Name') ? null : session('name');
            @endphp

            <input type="hidden" name="id" value="{{ session('input.id') ?? session('bulletin.id')  }}">
            <input type="hidden" name="password" value="{{ session('input.password') ?? session('bulletin.password') }}">

            <div class="form-group">
              <label>Name</label>
              <input type="text" class="form-control" name="name" value="{{ session('input.name') ?? $name }}">
            </div>
            <div class="form-group">
              <label>Title</label>
              <input type="text" class="form-control" name="title" value="{{  session('input.title') ?? session('bulletin.title') }}">
            </div>
            <div class="form-group">
              <label>Body</label>
              <textarea rows="5" class="form-control" name="message">{{ session('input.message') ?? session('bulletin.message') }}</textarea>
            </div>
            <div class="form-group row">
              <div class="col-md-4">
                <img class="img-responsive" alt="Image Post" src="{{ session('image') }}">
              </div>
              <div class="col-md-8 pl-0">
                <label>Choose image from your computer :</label>
                <div class="input-group">
                  <input type="text" class="form-control upload-form" value="No file chosen" readonly>
                  <span class="input-group-btn">
                    <span class="btn btn-default btn-file">
                      <i class="fa fa-folder-open"></i>&nbsp;Browse <input type="file" name="image" value="{{ session('input.image') ?? session('bulletin.image') }}">
                    </span>
                  </span>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox" name="delete">Delete image
                  </label>
                </div>
              </div>
            </div>

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div>

        </form>

      </div>
    </div>
  </div>

  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Delete Data</h4>
        </div>

        <div class="modal-body pad-20">
          <p>Are you sure want to delete this item?</p>
        </div>

        <div class="modal-footer">

          <form action="{{ route('bulletin.destroy', $id) }}" method="post">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            @method('DELETE')
            @csrf
            <input type="hidden" name="password" value="{{ session('bulletin.password') }}">
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>

        </div>

      </div>
    </div>
  </div>

@endif

<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-body">
        <div class="alert alert-danger" role="alert">
          <h4 class="alert-heading"><strong>Whoops!</strong></h4>
          <p><strong>{{ session('error') }}</strong></p>
        </div>

        @if (!is_null(session('method')))

          @if (session('method') === 'edit')
            <div class="form-group">
              <label>Name</label>
              <input type="text" class="form-control" name="name" value="{{ session('bulletin.name') }}" disabled>
            </div>

            <div class="form-group">
              <label>Title</label>
              <input type="text" class="form-control" name="title" value="{{ session('bulletin.title') }}" disabled>
            </div>

            <div class="form-group">
              <label>Body</label>
              <textarea rows="5" class="form-control" name="message" disabled>{{ session('bulletin.message') }}</textarea>
            </div>
          @endif
          
          @if (session('showPasswordForm'))
            @include ('bulletin-board.components.password-modal')
          @endif

        @endif

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>

    </div>
  </div>
</div>

resources/views/bulletin-board/components/password-modal.blade.php
@php $id = $bulletin->id ?? session('bulletin.id') @endphp

<form class="form-inline mt-30" method="get">
  @csrf

  <div class="form-group mx-sm-3 mb-2">
    <label for="inputPassword2" class="sr-only">Password</label>
    <input type="password" class="form-control" name="password" id="inputPassword2" placeholder="Password">
    <input type="hidden" name="id" value="{{ $id }}">
  </div>

  @if (session('method') === 'edit')
    <button type="submit" name="method" value="edit" class="btn btn-primary mb-2" data-toggle="modal" formaction="{{ route('bulletin.edit', $id) }}">Edit</button>
  @else
    <button type="submit" name="method" value="delete" class="btn btn-danger mb-2" data-toggle="modal" formaction="{{ route('bulletin.destroy', $id) }}">Delete</button>
  @endif

</form>

resources/views/bulletin-board/components/password.blade.php
@php $id = $bulletin->id ?? session('bulletin.id') @endphp

<form class="form-inline mt-30" method="get">
	@csrf
  <input type="hidden" name="id" value="{{ $id }}">

  @auth
  
    @if (! is_null($bulletin->user_id) )
      <button type="submit" name="method" value="edit" class="btn btn-default mb-2" data-toggle="modal" formaction="{{ route('bulletin.edit', $id) }}"><i class="fa fa-pencil p-3"></i></button>
      <button type="submit" name="method" value="delete" class="btn btn-danger mb-2" data-toggle="modal" formaction="{{ route('bulletin.delete', $id) }}"><i class="fa fa-trash p-3"></i></button>
    @endif

  @else

    @if ( is_null($bulletin->user_id) )
      <div class="form-group mx-sm-3 mb-2">
        <label for="inputPassword2" class="sr-only">Password</label>
        <input type="password" class="form-control" name="password" id="inputPassword2" placeholder="Password">
      </div>

      <button type="submit" name="method" value="edit" class="btn btn-default mb-2" data-toggle="modal" formaction="{{ route('bulletin.edit', $id) }}"><i class="fa fa-pencil p-3"></i></button>
      <button type="submit" name="method" value="delete" class="btn btn-danger mb-2" data-toggle="modal" formaction="{{ route('bulletin.delete', $id) }}"><i class="fa fa-trash p-3"></i></button>
    @endif

  @endauth
</form>

resources/views/bulletin-board/components/post.blade.php
@foreach ($bulletins as $bulletin)
  <div class="post">
    <div class="clearfix">

      <div class="pull-left">
        <h2 class="mb-5 text-green">
          <b>{{ $bulletin->name ?? 'No Name' }}</b>
        </h2>
      </div>

      <div class="pull-right text-right">
        <p class="text-lgray">
          {{ $bulletin->created_at->format('d-m-Y') }}
          <br/>
          <span class="small">{{ $bulletin->created_at->format('H:i') }}</span>
        </p>
      </div>

    </div>

    <h4 class="mb-20">{{ $bulletin->title }}</h4>
    <p class="mb-20">{!! nl2br($bulletin->message) !!}</p>
    <img class="img-responsive" src="{{ $render($bulletin->image->name) }}" alt="">

    @include('bulletin-board.components.password')
  </div>
@endforeach